const MARKER_ICON_URL =
    "https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-black.png";

const MARKER_SHADOW_URL =
    "https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png";

const COLORS = {
    olly: "blue",
    dad: "green",
    charlie: "red",
};

const HIKE_DATA = [
    {
        name: "First trip starting from the north end",
        sections: [
            {
                start: "Minehead",
                end: "Porlock Weir",
                direction: "S",
                startCoords: [51.2154, -3.4773],
                endCoords: [51.2178, -3.6266],
                charlie: true,
                olly: true,
                dad: true,
                videoLink: "https://www.youtube.com/watch?v=bePFuryxKWk",
                date: "2021-08-22",
            },
            {
                start: "Porlock Weir",
                end: "Lynmouth",
                direction: "S",
                startCoords: [51.2178, -3.6266],
                endCoords: [51.2296, -3.8292],
                charlie: true,
                olly: true,
                dad: true,
                videoLink: "https://www.youtube.com/watch?v=LeV3sTSMqbw",
                date: "2021-08-23",
            },
            {
                start: "Lynmouth",
                end: "Coombe Martin",
                direction: "S",
                startCoords: [51.2296, -3.8292],
                endCoords: [51.1995, -4.0243],
                charlie: true,
                olly: true,
                dad: true,
                videoLink: "https://www.youtube.com/watch?v=3lI0qnjOysM",
                date: "2021-08-24",
            },
            {
                start: "Coombe Martin",
                end: "Mortehoe",
                direction: "S",
                startCoords: [51.1995, -4.0243],
                endCoords: [51.1853, -4.2089],
                charlie: true,
                olly: true,
                dad: true,
                videoLink: "https://www.youtube.com/watch?v=VPTrw9T-YeQ",
                date: "2021-08-26",
            },
            {
                start: "Mortehoe",
                end: "Croyde",
                direction: "S",
                startCoords: [51.1853, -4.2089],
                endCoords: [51.13, -4.2244],
                charlie: true,
                olly: true,
                dad: true,
                videoLink: "https://www.youtube.com/watch?v=eb7Jj3PwDmA",
                date: "2021-08-27",
            },
        ],
    },

    {
        name: "Charlie and Dad start the south end",
        sections: [
            {
                start: "Shell Bay",
                end: "Swanage",
                direction: "S",
                startCoords: [50.6773, -1.9466],
                endCoords: [50.6083, -1.9608],
                charlie: true,
                olly: false,
                dad: true,
                videoLink: "https://youtu.be/pssL93hjxH0",
                fixEnd: true,
                date: "2022-04-29",
            },
            {
                start: "Dancing Ledge",
                end: "Swanage",
                direction: "N",
                startCoords: [50.592487, -2.00549],
                endCoords: [50.6083, -1.9608],
                charlie: true,
                olly: false,
                dad: true,
                videoLink: "https://youtu.be/BkH-Z1v7gkM",
                date: "2022-04-30",
            },
        ]
    },

    {
        name: "Charlie and Dad continue from the south but skip Lulworth",
        sections: [
            {
                start: "Osmington Mills",
                end: "Lulworth Cove",
                direction: "N",
                startCoords: [50.6346, -2.3753],
                endCoords: [50.6182, -2.247],
                charlie: true,
                olly: false,
                dad: true,
                videoLink: "",
                date: "2022-06-06",
            },
            {
                start: "Ferrybridge",
                end: "Osmington Mills",
                direction: "N",
                startCoords: [50.5860971, -2.474905],
                endCoords: [50.6346, -2.3753],
                charlie: true,
                olly: false,
                dad: true,
                videoLink: "",
                date: "2022-06-07",
            },
            {
                start: "Portland Loop",
                end: "Ferrybridge",
                direction: "N",
                startCoords: [50.5142, -2.4594],
                endCoords: [50.5860971, -2.474905],
                charlie: true,
                olly: false,
                dad: true,
                videoLink: "",
                date: "2022-06-08",
            },
        ],
    },

    {
        name: "Charlie and Dad continue from Portland",
        sections: [
            {
                start: "Bagwell Farm",
                end: "Portland Loop",
                direction: "S",
                startCoords: [50.633, -2.5297],
                endCoords: [50.5142, -2.4594],
                charlie: true,
                olly: false,
                dad: true,
                videoLink: "",
                date: "2022-06-28",
            },
            {
                start: "West Bexington",
                end: "Bagwell Farm",
                direction: "S",
                startCoords: [50.679, -2.6615],
                endCoords: [50.633, -2.5297],
                charlie: true,
                olly: false,
                dad: true,
                videoLink: "",
                date: "2022-06-29",
            },
            {
                start: "West Bay",
                end: "West Bexington",
                direction: "N",
                startCoords: [50.7117, -2.7636],
                endCoords: [50.679, -2.6615],
                charlie: true,
                olly: false,
                dad: true,
                videoLink: "",
                date: "2022-06-30",
            },
        ]
    },

    {
        name: "Dad and Olly fill out the next section in the north",
        sections: [
            {
                start: "Croyde",
                end: "Braunton",
                direction: "S",
                startCoords: [51.13, -4.2244],
                endCoords: [51.108, -4.161],
                charlie: false,
                olly: true,
                dad: true,
                videoLink: "https://youtu.be/vkObBdERalg",
                date: "2022-07-11",
            },
            {
                start: "Braunton",
                end: "Yelland",
                direction: "S",
                startCoords: [51.108, -4.161],
                endCoords: [51.0688, -4.1524],
                charlie: false,
                olly: true,
                dad: true,
                videoLink: "https://youtu.be/vkObBdERalg",
                fixEnd: false,
                date: "2022-07-12",
            },
            {
                start: "Yelland",
                end: "Bideford",
                startCoords: [51.0688, -4.1524],
                endCoords: [51.0228, -4.2029],
                charlie: false,
                olly: true,
                dad: true,
                videoLink: "https://youtu.be/vkObBdERalg",
                fixEnd: true,
                date: "2022-07-13",
            }
        ],
    },

    {
        name: "Everyone does the next section of the south",
        sections: [
            {
                start: "Lyme Regis",
                end: "West Bay",
                direction: "S",
                startCoords: [50.7252, -2.9366],
                endCoords: [50.7117, -2.7636],
                charlie: true,
                olly: true,
                dad: true,
                videoLink: "https://youtu.be/vB_wt8IAkLQ",
                date: "2022-08-02",
            },
            {
                start: "Seaton",
                end: "Lyme Regis",
                direction: "N",
                startCoords: [50.7053, -3.0719],
                endCoords: [50.7252, -2.9366],
                charlie: true,
                olly: true,
                dad: true,
                videoLink: "https://youtu.be/vB_wt8IAkLQ",
                date: "2022-08-03",
            },
        ],
    },

    {
        name: "Charlie and Dad go back to fill in the Lulworth section",
        sections: [
            {
                start: "Kimmeridge",
                end: "Dancing Ledge",
                direction: "S",
                startCoords: [50.6177, -2.1171],
                endCoords: [50.592487, -2.00549],
                charlie: true,
                olly: false,
                dad: true,
                videoLink: "https://youtu.be/6s6D9ETbP6A",
                date: "2023-03-31",
            },
            {
                start: "Lulworth Cove",
                end: "Kimmeridge",
                direction: "N",
                startCoords: [50.6182, -2.247],
                endCoords: [50.6177, -2.1171],
                charlie: true,
                olly: false,
                dad: true,
                videoLink: "https://youtu.be/S9_UuzV5GMI",
                date: "2023-04-01",
            },
        ],
    },

    {
        name: "Everyone does the next section from Seaton (with the dog!)",
        sections: [
            {
                start: "Sidmouth",
                end: "Seaton",
                direction: "S",
                startCoords: [50.6787, -3.2376],
                endCoords: [50.7053, -3.0719],
                charlie: true,
                olly: true,
                dad: true,
                videoLink: "",
                date: "2023-04-10",
            },      
            {
                start: "Sidmouth",
                end: "Budleigh Salterton",
                direction: "S",
                startCoords: [50.6787, -3.2376],
                endCoords: [50.63, -3.3163],
                charlie: true,
                olly: true,
                dad: true,
                videoLink: "",
                date: "2023-04-11",
            },      
            {
                start: "Budleigh Salterton",
                end: "Exmouth",
                direction: "N",
                startCoords: [50.63, -3.3163],
                endCoords: [50.6219, -3.4161],
                charlie: true,
                olly: true,
                dad: true,
                videoLink: "",
                date: "2023-04-12",
            },
            {
                start: "Teignmouth",
                end: "Exmouth",
                direction: "N",
                endCoords: [50.6219, -3.4161],
                startCoords: [50.5403, -3.5036],
                charlie: true,
                olly: true,
                dad: true,
                videoLink: "",
                date: "2023-04-13",
            },
        ]
    },

    {
        // TODO: Pretty sure there is no video for this section
        name: "Dad does a random solo walk in Cornwall",
        sections: [
            {
                start: "Trevaunance Cove",
                end: "Portreath",
                direction: "N",
                startCoords: [50.319018, -5.202245],
                endCoords: [50.260853, -5.292442],
                charlie: false,
                olly: false,
                dad: true,
                videoLink: "none",
                fixEnd: true,
                date: "2023-07-03",
            },
        ],
    },

    {
        // TODO: Pretty sure there is no video for this section
        name: "Everyone fills out a new disconnected section around Newquay",
        sections: [
            {
                start: "Holywell",
                end: "Trevaunance Cove",
                direction: "S",
                startCoords: [50.385772, -5.14256],
                endCoords: [50.319018, -5.202245],
                charlie: true,
                dad: true,
                olly: true,
                videoLink: "none",
                date: "2023-07-04",
            },
            {
                start: "Holywell",
                end: "Newquay",
                direction: "N",
                startCoords: [50.385772, -5.14256],
                endCoords: [50.415142, -5.076412],
                charlie: true,
                dad: true,
                olly: true,
                videoLink: "none",
                fixEnd: true,
                date: "2023-07-05",
            },
            {
                start: "Watergate Bay",
                end: "Newquay",
                direction: "S",
                startCoords: [50.444544, -5.040023],
                endCoords: [50.415142, -5.076412],
                charlie: true,
                dad: true,
                olly: true,
                videoLink: "none",
                date: "2023-07-06",
            },
        ]
    },
    
    {
        name: "Charlie and Dad tackle more of the new middle section",
        sections: [
            {
                start: "Porthcothan",
                end: "Harlyn Bay",
                direction: "N",
                startCoords: [50.508091, -5.021389],
                endCoords: [50.53947, -4.993452],
                charlie: true,
                dad: true,
                olly: false,
                videoLink: "https://youtu.be/y5YhAAPxWMM",
                date: "2024-01-28",
            },
            {
                start: "Harlyn Bay",
                end: "Padstow",
                direction: "N",
                startCoords: [50.53947, -4.993452],
                endCoords: [50.538812, -4.936418],
                charlie: true,
                dad: true,
                olly: false,
                videoLink: "https://youtu.be/jGyB_yDCq4o",
                fixEnd: true,
                date: "2024-01-29",
            },
            {
                start: "Watergate Bay",
                end: "Porthcothan",
                direction: "N",
                startCoords: [50.444544, -5.040023],
                endCoords: [50.508091, -5.021389],
                charlie: true,
                dad: true,
                olly: false,
                videoLink: "https://youtu.be/x4pgyRBNXpo",
                date: "2024-01-31",
            },
            {
                start: "Rock",
                end: "Pentireglaze Lead Mines",
                direction: "N",
                startCoords: [50.54139, -4.90967],
                endCoords: [50.581758, -4.905161],
                charlie: true,
                dad: true,
                olly: false,
                videoLink: "https://youtu.be/210oNvf5OMc",
                date: "2024-02-01",
                fixEnd: true,
            },
        ]
    },

    {
        name: "Everyone continues from the progress made at the south end",
        sections: [
            {
                start: "Teignmouth",
                end: "Torquay",
                direction: "S",
                startCoords: [50.5403, -3.5036],
                endCoords: [50.4602, -3.5405],
                charlie: true,
                olly: true,
                dad: true,
                videoLink: "",
                fixEnd: true,
                date: "2025-08-26",
            },
            {
                start: "Torquay",
                end: "Brixham",
                direction: "S",
                startCoords: [50.4602, -3.5405],
                endCoords: [50.4007, -3.5162],
                charlie: true,
                olly: true,
                dad: true,
                videoLink: "",
                fixEnd: true,
                date: "2025-08-27",
            },
            {
                start: "Brixham",
                end: "Scabbacombe Beach",
                direction: "S",
                startCoords: [50.4007, -3.5162],
                endCoords: [50.3587, -3.5217],
                charlie: true,
                olly: true,
                dad: true,
                videoLink: "",
                fixEnd: true,
                date: "2025-08-28",
            },
            {
                start: "Scabbacombe Beach",
                end: "Dartmouth",
                direction: "S",
                startCoords: [50.3587, -3.5217],
                endCoords: [50.349, -3.5777],
                charlie: true,
                olly: true,
                dad: true,
                videoLink: "",
                fixEnd: true,
                date: "2025-08-30",
            },
        ],
    },
];
